author: Dale Zak
name: Trello-integration-action
description: GitHub Action to attach GitHub branch and pull requests to a Trello card
branding:
  icon: 'check-square'  
  color: 'gray-dark'
inputs:
  trello-api-key:
    description: Trello API key, visit https://trello.com/app-key for key
    required: true
  trello-auth-token:
    description: Trello auth token, visit https://trello.com/app-key then click generate a token
    required: true
  trello-board-reopen-list-id:
    description: Trello auth token, visit https://trello.com/app-key then click generate a token
    required: false
  trello-board-needs-code-review-list-id:
    description: Trello auth token, visit https://trello.com/app-key then click generate a token
    required: false
  trello-board-needs-acceptation-list-id:
    description: Trello auth token, visit https://trello.com/app-key then click generate a token
    required: false
runs:
  using: node12
  main: dist/index.js